/**
 * VITAS · Strings de los fallbacks deterministas de agentes (multi-idioma)
 *
 * Los fallbacks corren en el servidor (edge, sin react-i18next) cuando el LLM no
 * está disponible. Sus textos user-facing viven aquí, por idioma. Es la variante
 * server-side del i18n: añadir un idioma = añadir su bloque (si falta, se cae al
 * idioma por defecto — nunca rompe).
 */

import { normalizeLocale, DEFAULT_LOCALE, type ReportLocale } from "../../src/lib/shared/locale";

interface FallbackStrings {
  // Role profile
  roleRiskUnavailable: string;
  roleGap: (metric: string, value: number) => string;
  roleSummary: (name: string, identity: string) => string;
  // Scout insight
  scoutSummaryHead: (name: string) => string;
  scoutSummaryBody: (vsi: number, trend: string) => string;
  scoutBreakoutHead: (name: string) => string;
  scoutBreakoutBody: (vsi: number) => string;
  scoutPhvHead: (name: string) => string;
  scoutPhvBody: (speed: number) => string;
  scoutDrillHead: (name: string, metric: string) => string;
  scoutDrillBody: (max: number, metric: string) => string;
  scoutRegressionHead: (name: string) => string;
  scoutRegressionBody: (vsi: number) => string;
  scoutBalancedHead: (name: string) => string;
  scoutBalancedBody: string;
  metricFallbackName: string;
  playerTag: string;
  scoutActionItems: string[];
}

const STRINGS: Record<string, FallbackStrings> = {
  es: {
    roleRiskUnavailable: "Resultado aproximado — análisis IA no disponible",
    roleGap: (m, v) => `${m} necesita mejora (${v})`,
    roleSummary: (name, id) =>
      `Perfil generado por reglas determinísticas para ${name}. Identidad dominante: ${id}. Se recomienda ejecutar análisis con IA para mayor precisión.`,
    scoutSummaryHead: (name) => `Resumen de ${name}`,
    scoutSummaryBody: (vsi, trend) => `VSI actual: ${vsi}. Tendencia: ${trend}.`,
    scoutBreakoutHead: (name) => `${name} muestra progresión destacada`,
    scoutBreakoutBody: (vsi) =>
      `VSI de ${vsi} con tendencia ascendente. Jugador en fase de despegue, monitorizar de cerca para optimizar su desarrollo.`,
    scoutPhvHead: (name) => `Alerta PHV: ${name} en ventana crítica`,
    scoutPhvBody: (speed) =>
      `Madurador tardío (aún pre-PHV) con velocidad ${speed}: rendimiento notable sin ventaja madurativa — señal de talento. Priorizar técnica sobre carga física.`,
    scoutDrillHead: (name, metric) => `${name} destaca en ${metric}`,
    scoutDrillBody: (max, metric) => `Valor de ${max} en ${metric}. Potenciar esta fortaleza con ejercicios específicos.`,
    scoutRegressionHead: (name) => `${name}: descenso en rendimiento`,
    scoutRegressionBody: (vsi) => `VSI de ${vsi} con tendencia descendente. Revisar carga de entrenamiento y factores externos.`,
    scoutBalancedHead: (name) => `${name}: perfil equilibrado`,
    scoutBalancedBody: "Métricas homogéneas entre 55-75. Buscar especialización en una dimensión clave.",
    metricFallbackName: "métrica",
    playerTag: "jugador",
    scoutActionItems: [
      "Revisar métricas en la próxima sesión",
      "Comparar con jugadores de la misma edad y posición",
    ],
  },
  en: {
    roleRiskUnavailable: "Approximate result — AI analysis unavailable",
    roleGap: (m, v) => `${m} needs improvement (${v})`,
    roleSummary: (name, id) =>
      `Profile generated by deterministic rules for ${name}. Dominant identity: ${id}. Running the AI analysis is recommended for higher accuracy.`,
    scoutSummaryHead: (name) => `${name} summary`,
    scoutSummaryBody: (vsi, trend) => `Current VSI: ${vsi}. Trend: ${trend}.`,
    scoutBreakoutHead: (name) => `${name} shows notable progression`,
    scoutBreakoutBody: (vsi) =>
      `VSI of ${vsi} trending up. Player in a breakout phase — monitor closely to optimise development.`,
    scoutPhvHead: (name) => `PHV alert: ${name} in a critical window`,
    scoutPhvBody: (speed) =>
      `Late maturer (still pre-PHV) with speed ${speed}: notable output without a maturity advantage — a talent signal. Prioritise technique over physical load.`,
    scoutDrillHead: (name, metric) => `${name} stands out in ${metric}`,
    scoutDrillBody: (max, metric) => `Value of ${max} in ${metric}. Reinforce this strength with targeted drills.`,
    scoutRegressionHead: (name) => `${name}: performance drop`,
    scoutRegressionBody: (vsi) => `VSI of ${vsi} trending down. Review training load and external factors.`,
    scoutBalancedHead: (name) => `${name}: balanced profile`,
    scoutBalancedBody: "Even metrics between 55-75. Seek specialisation in a key dimension.",
    metricFallbackName: "metric",
    playerTag: "player",
    scoutActionItems: [
      "Review metrics in the next session",
      "Compare with players of the same age and position",
    ],
  },
};

/** Devuelve el bloque de strings del idioma pedido (fallback al idioma por defecto). */
export function fallbackStrings(locale: unknown): FallbackStrings {
  const code: ReportLocale = normalizeLocale(locale);
  return STRINGS[code] ?? STRINGS[DEFAULT_LOCALE];
}
